"""Canonical read-only dormant-memory retrieval senses."""

from .evidence_bridge import (
    AUTHORITATIVE_FILES,
    DEFAULT_INDEX_RELATIVE,
    INDEX_MANIFEST_SCHEMA,
    INDEX_SCHEMA,
    CorpusFileBinding,
    DormantCorpus,
    DormantCorpusBinding,
    DormantCorpusError,
    DormantEvidenceBridge,
    DormantEvidenceError,
    DormantEvidenceIndex,
    DormantQueryError,
    DormantRecordIntegrityError,
    EvidenceCandidate,
    StaleDormantIndexError,
    SurfacedDormantResult,
    VerifiedDormantContainer,
    VerifiedDormantEdge,
    VerifiedDormantEvidence,
    default_index_path,
)

__all__ = [
    "INDEX_SCHEMA",
    "INDEX_MANIFEST_SCHEMA",
    "DEFAULT_INDEX_RELATIVE",
    "AUTHORITATIVE_FILES",
    "DormantEvidenceError",
    "DormantCorpusError",
    "StaleDormantIndexError",
    "DormantRecordIntegrityError",
    "DormantQueryError",
    "CorpusFileBinding",
    "DormantCorpusBinding",
    "DormantCorpus",
    "EvidenceCandidate",
    "VerifiedDormantEdge",
    "VerifiedDormantContainer",
    "VerifiedDormantEvidence",
    "SurfacedDormantResult",
    "DormantEvidenceIndex",
    "DormantEvidenceBridge",
    "default_index_path",
]
