"""Canonical Axon shared-field contracts and deterministic D64 compiler.

Day Zero active surface only. Historical 384-slot views, schedule cursors,
schema-v2 experiments, and related compatibility code live under
``archive/day_zero_legacy_2026-08-20`` and are not imported here.
"""

from .compiler_d64 import (
    D64_COMPILER_SCHEMA,
    D64_LANES_PER_ROW,
    D64_WIDTH,
    SUBSTRATE_WIDTH,
    CanonicalCharAddress,
    CartographicSpan,
    CompiledD64Field,
    D64CharacterPage,
    D64CoverageManifest,
    D64FieldCompiler,
    FieldCompilerError,
    IncompleteRailError,
    StaleCompiledFieldError,
    UnsupportedActiveCharacterError,
    apply_compiled_delta,
    replacement_delta,
)
from .delta import (
    DeleteOperation,
    DeleteText,
    DeltaValidationError,
    FieldDelta,
    FieldOperation,
    InsertOperation,
    InsertText,
    OverlappingDeltaError,
    ReplaceOperation,
    ReplaceText,
    SealedRegionWriteError,
    StaleDeltaError,
    apply_delta,
    replay_deltas,
    validate_delta,
)
from .schema import (
    AttendedInterval,
    CANONICAL_REGION_ORDER,
    CORE_WRITABLE_REGIONS,
    LOGICAL_REGION_IDS,
    RegionMaskPolicy,
    SCHEMA_VERSION,
    FieldSpan,
    LogicalRegion,
    PhysicalRole,
    RegionState,
    RegionVisibility,
    SharedFieldSnapshot,
    WritePolicy,
    canonical_json_bytes,
    canonical_sha256,
    resolve_mask_policy,
)
from .state_branch import (
    BRANCH_EVENT_SCHEMA,
    BRANCH_HEAD_SCHEMA,
    BRANCH_SCHEMA,
    BranchAuthorityError,
    BranchHead,
    BranchIntegrityError,
    CanonicalStateBranch,
    CanonicalStateBranchError,
)

__all__ = [
    "SCHEMA_VERSION",
    "LogicalRegion",
    "CANONICAL_REGION_ORDER",
    "LOGICAL_REGION_IDS",
    "RegionVisibility",
    "WritePolicy",
    "AttendedInterval",
    "RegionMaskPolicy",
    "resolve_mask_policy",
    "PhysicalRole",
    "CORE_WRITABLE_REGIONS",
    "FieldSpan",
    "RegionState",
    "SharedFieldSnapshot",
    "canonical_json_bytes",
    "canonical_sha256",
    "D64_COMPILER_SCHEMA",
    "D64_WIDTH",
    "SUBSTRATE_WIDTH",
    "D64_LANES_PER_ROW",
    "FieldCompilerError",
    "UnsupportedActiveCharacterError",
    "IncompleteRailError",
    "StaleCompiledFieldError",
    "CanonicalCharAddress",
    "CartographicSpan",
    "D64CoverageManifest",
    "D64CharacterPage",
    "CompiledD64Field",
    "D64FieldCompiler",
    "replacement_delta",
    "apply_compiled_delta",
    "BRANCH_SCHEMA",
    "BRANCH_HEAD_SCHEMA",
    "BRANCH_EVENT_SCHEMA",
    "CanonicalStateBranchError",
    "BranchIntegrityError",
    "BranchAuthorityError",
    "BranchHead",
    "CanonicalStateBranch",
    "DeltaValidationError",
    "StaleDeltaError",
    "SealedRegionWriteError",
    "OverlappingDeltaError",
    "InsertText",
    "DeleteText",
    "ReplaceText",
    "InsertOperation",
    "DeleteOperation",
    "ReplaceOperation",
    "FieldOperation",
    "FieldDelta",
    "validate_delta",
    "apply_delta",
    "replay_deltas",
]
