"""Canonical Axon shared-field contracts: exact characters, regions, masks, deltas.

The canonical body is exactly the 95-character substrate (anything else fails
closed). The Heart serves it as exact 16D cells (see d16_view). There is no
packing and no model-width compilation. The active canonical schema is
shared-field-v4; a multi-core output region is expected to arrive with the next
schema version.
"""

from .d16_view import (
    D16CellAddress,
    D16RegionPatch,
    D16RegionView,
    D16ResyncRequired,
    D16View,
    D16ViewDelta,
    D16ViewError,
    D16ViewIdentity,
    D16_VIEW_DELTA_SCHEMA,
    D16_VIEW_SCHEMA,
    D16_WIDTH,
    materialize_d16_view,
)
from .delta import (
    DeleteOperation,
    DeleteText,
    DeltaValidationError,
    FieldDelta,
    FieldOperation,
    InsertOperation,
    InsertText,
    OverlappingDeltaError,
    ReplaceOperation,
    ReplaceText,
    SealedRegionWriteError,
    StaleDeltaError,
    apply_delta,
    replacement_delta,
    replay_deltas,
    validate_delta,
)
from .schema import (
    CANONICAL_REGION_ORDER,
    CORE_WRITABLE_REGIONS,
    CORTEX_SCHEMA_VERSION,
    IDENTITY_REGION_ORDER,
    IDENTITY_SCHEMA_VERSION,
    LEGACY_CORTEX_REGION_NAME,
    LEGACY_SCHEMA_VERSION,
    LOGICAL_REGION_IDS,
    PRE_IDENTITY_REGION_ORDER,
    SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    TRAINING_REGIONS,
    AttendedInterval,
    FieldSpan,
    LogicalRegion,
    PhysicalRole,
    RegionMaskPolicy,
    RegionState,
    RegionVisibility,
    SharedFieldSnapshot,
    WritePolicy,
    canonical_json_bytes,
    canonical_region_order,
    canonical_sha256,
    resolve_mask_policy,
)
from .state_branch import (
    BRANCH_EVENT_SCHEMA,
    BRANCH_HEAD_SCHEMA,
    BRANCH_SCHEMA,
    BranchAuthorityError,
    BranchHead,
    BranchIntegrityError,
    CanonicalStateBranch,
    CanonicalStateBranchError,
    field_delta_from_canonical_dict,
    snapshot_from_canonical_dict,
)

__all__ = [
    "BRANCH_EVENT_SCHEMA",
    "BRANCH_HEAD_SCHEMA",
    "BRANCH_SCHEMA",
    "CANONICAL_REGION_ORDER",
    "CORE_WRITABLE_REGIONS",
    "CORTEX_SCHEMA_VERSION",
    "D16CellAddress",
    "D16RegionPatch",
    "D16RegionView",
    "D16ResyncRequired",
    "D16View",
    "D16ViewDelta",
    "D16ViewError",
    "D16ViewIdentity",
    "D16_VIEW_DELTA_SCHEMA",
    "D16_VIEW_SCHEMA",
    "D16_WIDTH",
    "IDENTITY_REGION_ORDER",
    "IDENTITY_SCHEMA_VERSION",
    "LEGACY_CORTEX_REGION_NAME",
    "LEGACY_SCHEMA_VERSION",
    "LOGICAL_REGION_IDS",
    "PRE_IDENTITY_REGION_ORDER",
    "SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "TRAINING_REGIONS",
    "AttendedInterval",
    "BranchAuthorityError",
    "BranchHead",
    "BranchIntegrityError",
    "CanonicalStateBranch",
    "CanonicalStateBranchError",
    "DeleteOperation",
    "DeleteText",
    "DeltaValidationError",
    "FieldDelta",
    "FieldOperation",
    "FieldSpan",
    "InsertOperation",
    "InsertText",
    "LogicalRegion",
    "OverlappingDeltaError",
    "PhysicalRole",
    "RegionMaskPolicy",
    "RegionState",
    "RegionVisibility",
    "ReplaceOperation",
    "ReplaceText",
    "SealedRegionWriteError",
    "SharedFieldSnapshot",
    "StaleDeltaError",
    "WritePolicy",
    "apply_delta",
    "canonical_json_bytes",
    "canonical_region_order",
    "canonical_sha256",
    "field_delta_from_canonical_dict",
    "replacement_delta",
    "replay_deltas",
    "resolve_mask_policy",
    "materialize_d16_view",
    "snapshot_from_canonical_dict",
    "validate_delta",
]
