"""Axon Trainer organ parameter authority and candidate-learning contracts.

Live registered organs remain sealed from direct optimization.  Governed
learning occurs only on isolated candidate generations with exact lineage,
telemetry, checkpoints, deterministic evaluation gates, and non-activating
promotion proposals.
"""
from .activation import (
    ACTIVE_GENERATION_POINTER_SCHEMA,
    GENERATION_SNAPSHOT_SCHEMA,
    PARAMETER_ACTIVATION_SCHEMA,
    PARAMETER_ROLLBACK_SCHEMA,
    ActiveGenerationPointer,
    GenerationSnapshotRecord,
    ParameterActivationReceipt,
    ParameterRollbackReceipt,
)
from .authority import (
    AUTHORIZED_MUTATION_SCHEMA,
    AuthorizedParameterMutation,
    ParameterAuthorityError,
    authorize_parameter_mutation,
)
from .contracts import (
    PARAMETER_GRANT_SCHEMA,
    PARAMETER_INVENTORY_SCHEMA,
    PARAMETER_MANIFEST_SCHEMA,
    PARAMETER_MODULE_SCHEMA,
    PARAMETER_PLAN_SCHEMA,
    PARAMETER_PROMOTION_SCHEMA,
    PARAMETER_TENSOR_SCHEMA,
    TRAINER_PARAMETER_SCHEMA,
    OrganKind,
    ParameterInventory,
    ParameterModuleDescriptor,
    ParameterModuleManifest,
    ParameterMutationGrant,
    ParameterMutationPlan,
    ParameterMutationPolicy,
    ParameterPromotionProposal,
    ParameterTensorRecord,
    TrainerCoreRole,
)
from .execution import CandidateOptimizationSession, OptimizerExecutionPolicy, TrainerExecutionError
from .gates import (
    EVALUATION_OBSERVATION_SCHEMA,
    EVALUATION_REQUIREMENT_SCHEMA,
    PROMOTION_GATE_DECISION_SCHEMA,
    PROMOTION_GATE_SCHEMA,
    EvaluationObservation,
    EvaluationRequirement,
    MetricComparison,
    PromotionGate,
    PromotionGateDecision,
    evaluate_promotion_gate,
)
from .host import TrainerControlPlane
from .inspection import TRAINER_INSPECTION_SCHEMA, TrainerInspectionSnapshot, inspect_trainer_state
from .learning import (
    LEARNING_POLICY_SCHEMA,
    GovernedLearningPolicy,
    OptimizerKind,
    PrecisionMode,
    SchedulerKind,
)
from .lease import TrainerLeaseDeniedError, TrainerWriterLease
from .lifecycle import (
    CANDIDATE_CHECKPOINT_SCHEMA,
    CANDIDATE_LIFECYCLE_SCHEMA,
    LEARNING_MICROSTEP_SCHEMA,
    OPTIMIZATION_STEP_SCHEMA,
    CandidateCheckpointRecord,
    CandidateLifecycleEvent,
    CandidateStatus,
    LearningMicrostepReceipt,
    OptimizationStepReceipt,
)
from .registry import (
    IncompleteParameterInventoryError,
    ParameterRegistry,
    ParameterRegistryError,
    capture_module_manifest,
    descriptors_share_anatomy,
    parameter_value_sha256,
)
from .preflight import (
    REQUIRED_PREFLIGHT_EVIDENCE,
    TRAINING_BOUND_SCHEMA,
    TRAINING_CAPACITY_CONTRACT_SCHEMA,
    TRAINING_PREFLIGHT_EVIDENCE_SCHEMA,
    TRAINING_PREFLIGHT_RECEIPT_SCHEMA,
    CompleteFieldTrainingContract,
    DeclaredTrainingBound,
    PreflightEvidenceKind,
    TrainingBoundCategory,
    TrainingPreflightEvidence,
    TrainingPreflightReceipt,
    build_training_preflight_receipt,
)
from .sessions import (
    TRAINER_SESSION_EXAMPLE_SCHEMA,
    TRAINER_SESSION_POLICY_SCHEMA,
    TRAINER_SESSION_SCHEMA,
    LivedExperienceSessionCompiler,
    TrainerSessionExample,
    TrainerSessionManifest,
    TrainerSessionPolicy,
)
from .store import TrainerStateStore, TrainerStoreError
from .telemetry import (
    PARAMETER_STAT_SCHEMA,
    PARAMETER_TELEMETRY_SCHEMA,
    ParameterStat,
    ParameterTelemetryFrame,
    capture_parameter_telemetry,
)

__all__ = [
    "TRAINER_SESSION_EXAMPLE_SCHEMA",
    "TRAINER_SESSION_POLICY_SCHEMA",
    "TRAINER_SESSION_SCHEMA",
    "LivedExperienceSessionCompiler",
    "TrainerSessionExample",
    "TrainerSessionManifest",
    "TrainerSessionPolicy",
    "TRAINER_PARAMETER_SCHEMA",
    "ACTIVE_GENERATION_POINTER_SCHEMA",
    "GENERATION_SNAPSHOT_SCHEMA",
    "PARAMETER_ACTIVATION_SCHEMA",
    "PARAMETER_ROLLBACK_SCHEMA",
    "PARAMETER_MODULE_SCHEMA",
    "PARAMETER_TENSOR_SCHEMA",
    "PARAMETER_MANIFEST_SCHEMA",
    "PARAMETER_INVENTORY_SCHEMA",
    "PARAMETER_GRANT_SCHEMA",
    "PARAMETER_PLAN_SCHEMA",
    "PARAMETER_PROMOTION_SCHEMA",
    "AUTHORIZED_MUTATION_SCHEMA",
    "PARAMETER_STAT_SCHEMA",
    "PARAMETER_TELEMETRY_SCHEMA",
    "CANDIDATE_LIFECYCLE_SCHEMA",
    "CANDIDATE_CHECKPOINT_SCHEMA",
    "LEARNING_POLICY_SCHEMA",
    "LEARNING_MICROSTEP_SCHEMA",
    "OPTIMIZATION_STEP_SCHEMA",
    "EVALUATION_OBSERVATION_SCHEMA",
    "EVALUATION_REQUIREMENT_SCHEMA",
    "PROMOTION_GATE_SCHEMA",
    "PROMOTION_GATE_DECISION_SCHEMA",
    "TRAINER_INSPECTION_SCHEMA",
    "TRAINING_BOUND_SCHEMA",
    "TRAINING_CAPACITY_CONTRACT_SCHEMA",
    "TRAINING_PREFLIGHT_EVIDENCE_SCHEMA",
    "TRAINING_PREFLIGHT_RECEIPT_SCHEMA",
    "OrganKind",
    "ParameterMutationPolicy",
    "TrainerCoreRole",
    "OptimizerKind",
    "SchedulerKind",
    "PrecisionMode",
    "GovernedLearningPolicy",
    "TrainingBoundCategory",
    "PreflightEvidenceKind",
    "REQUIRED_PREFLIGHT_EVIDENCE",
    "DeclaredTrainingBound",
    "CompleteFieldTrainingContract",
    "TrainingPreflightEvidence",
    "TrainingPreflightReceipt",
    "build_training_preflight_receipt",
    "ParameterModuleDescriptor",
    "ParameterTensorRecord",
    "ParameterModuleManifest",
    "ParameterInventory",
    "ParameterMutationGrant",
    "ParameterMutationPlan",
    "ParameterPromotionProposal",
    "GenerationSnapshotRecord",
    "ActiveGenerationPointer",
    "ParameterActivationReceipt",
    "ParameterRollbackReceipt",
    "ParameterAuthorityError",
    "AuthorizedParameterMutation",
    "authorize_parameter_mutation",
    "ParameterRegistryError",
    "IncompleteParameterInventoryError",
    "capture_module_manifest",
    "descriptors_share_anatomy",
    "parameter_value_sha256",
    "ParameterRegistry",
    "ParameterStat",
    "ParameterTelemetryFrame",
    "capture_parameter_telemetry",
    "CandidateStatus",
    "CandidateLifecycleEvent",
    "CandidateCheckpointRecord",
    "LearningMicrostepReceipt",
    "OptimizationStepReceipt",
    "MetricComparison",
    "EvaluationObservation",
    "EvaluationRequirement",
    "PromotionGate",
    "PromotionGateDecision",
    "evaluate_promotion_gate",
    "TrainerExecutionError",
    "OptimizerExecutionPolicy",
    "CandidateOptimizationSession",
    "TrainerLeaseDeniedError",
    "TrainerWriterLease",
    "TrainerInspectionSnapshot",
    "inspect_trainer_state",
    "TrainerStoreError",
    "TrainerStateStore",
    "TrainerControlPlane",
]
