"""The Axon heart (Field Compiler Organ): control-plane contracts.

Build A surface: authority classes, core registry, heartbeat/tick identity,
frozen tick images, the noncanonical proposal board, and the heart
transaction boundary.  No neural code lives here; canonical mutation is
performed only through the existing typed-delta machinery in
``runtime.field.delta``.
"""

from .authority import (
    CONSOLIDATOR_GOVERNED_REGIONS,
    DEFAULT_CORE_GOVERNED_REGIONS,
    DORMANT_VALVE_GOVERNED_REGIONS,
    INGRESS_OWNED_REGIONS,
    AuthorityClass,
    AuthorityGrant,
    IngressChannel,
)
from .coordinator import (
    BeatConfig,
    BeatCoordinator,
    BeatResult,
    BeatState,
)
from .board import (
    ParticipantRecord,
    ParticipantState,
    Proposal,
    ProposalBoard,
    ProposalPass,
)
from .errors import (
    AuthorityViolationError,
    BarrierClosedError,
    BarrierNotReadyError,
    CoreCommitError,
    CoreRegistryError,
    DuplicateCoreError,
    DuplicateProposalError,
    FinalCommitAlreadyMadeError,
    HealthCorruptionError,
    HeartError,
    HeartTransactionError,
    HeartbeatError,
    HostStateError,
    LeaseDeniedError,
    IngressDuringTickError,
    InvalidAuthorityGrantError,
    NoActiveParticipantsError,
    ProposalBoardError,
    RailMembershipError,
    RailWidthMismatchError,
    StaleBaseProposalError,
    StaleRailBindingError,
    TickBindingError,
    UnknownCoreError,
    UnknownParticipantError,
    UnknownValveError,
    ValveAdmissionError,
    ValveAuthorityError,
    ValveBudgetExceededError,
    ValveClosedError,
    ValveDuringTickError,
    ValveSourceMismatchError,
    PoisonEventError,
    ReplayEventError,
)
from .durable_ingress import DurableIngressSpool, IngressRecord
from .health import HeartHealth, HealthJournal
from .host import HeartHost, HeartHostBeatResult, HeartHostConfig, HostBeatState
from .identity import HeartIdentity, HeartIdentityStore
from .intelligence import (
    CRITICAL_SEMANTIC_CLASSES,
    HEART_ENSEMBLE_POLICY_SCHEMA,
    HEART_FIDELITY_EVIDENCE_SCHEMA,
    HEART_PROMOTION_DECISION_SCHEMA,
    HEART_TRANSLATOR_SCHEMA,
    HeartEnsemblePolicy,
    HeartSemanticFidelityEvidence,
    HeartTranslationPromotionDecision,
    HeartTranslatorDescriptor,
    HeartTranslatorRole,
    HeartTranslatorState,
    evaluate_heart_translator_promotion,
)
from .ingress_queue import IngressItem, IngressQueue
from .lease import SingleWriterLease
from .registry import CoreDescriptor, CoreRegistry, CoreStatus
from .valve import (
    HeartValveDefinition,
    HeartValveRegistry,
    ValveBudget,
    ValveBudgetTracker,
    ValveDecision,
    ValveEnvelope,
    ValveReceipt,
    ValveState,
    primitive_valve_registry,
)
from .tick import (
    DERIVED_VIEW_SCHEMA,
    TICK_IDENTITY_SCHEMA,
    TICK_IMAGE_SCHEMA,
    FrozenTickImage,
    derive_view_id,
    HeartbeatClock,
    RailBinding,
    TickIdentity,
)
from .transaction import (
    COMMIT_SCHEMA,
    HeartCommit,
    HeartTransactionBoundary,
)

__all__ = [
    "AuthorityClass",
    "IngressChannel",
    "INGRESS_OWNED_REGIONS",
    "DORMANT_VALVE_GOVERNED_REGIONS",
    "CONSOLIDATOR_GOVERNED_REGIONS",
    "DEFAULT_CORE_GOVERNED_REGIONS",
    "AuthorityGrant",
    "BeatConfig",
    "BeatCoordinator",
    "BeatResult",
    "BeatState",
    "HostBeatState",
    "HeartHostConfig",
    "HeartHostBeatResult",
    "HeartHost",
    "IngressItem",
    "IngressQueue",
    "IngressRecord",
    "DurableIngressSpool",
    "HeartIdentity",
    "HeartIdentityStore",
    "HEART_TRANSLATOR_SCHEMA",
    "HEART_ENSEMBLE_POLICY_SCHEMA",
    "HEART_FIDELITY_EVIDENCE_SCHEMA",
    "HEART_PROMOTION_DECISION_SCHEMA",
    "CRITICAL_SEMANTIC_CLASSES",
    "HeartTranslatorRole",
    "HeartTranslatorState",
    "HeartTranslatorDescriptor",
    "HeartEnsemblePolicy",
    "HeartSemanticFidelityEvidence",
    "HeartTranslationPromotionDecision",
    "evaluate_heart_translator_promotion",
    "HeartHealth",
    "HealthJournal",
    "SingleWriterLease",
    "ValveState",
    "ValveBudget",
    "HeartValveDefinition",
    "ValveEnvelope",
    "ValveDecision",
    "ValveReceipt",
    "ValveBudgetTracker",
    "HeartValveRegistry",
    "primitive_valve_registry",
    "CoreStatus",
    "CoreDescriptor",
    "CoreRegistry",
    "TICK_IDENTITY_SCHEMA",
    "TICK_IMAGE_SCHEMA",
    "DERIVED_VIEW_SCHEMA",
    "derive_view_id",
    "TickIdentity",
    "HeartbeatClock",
    "RailBinding",
    "FrozenTickImage",
    "ProposalPass",
    "ParticipantState",
    "Proposal",
    "ParticipantRecord",
    "ProposalBoard",
    "COMMIT_SCHEMA",
    "HeartCommit",
    "HeartTransactionBoundary",
    "HeartError",
    "InvalidAuthorityGrantError",
    "AuthorityViolationError",
    "CoreRegistryError",
    "DuplicateCoreError",
    "UnknownCoreError",
    "NoActiveParticipantsError",
    "HeartbeatError",
    "StaleRailBindingError",
    "RailWidthMismatchError",
    "StaleBaseProposalError",
    "ProposalBoardError",
    "UnknownParticipantError",
    "DuplicateProposalError",
    "RailMembershipError",
    "BarrierNotReadyError",
    "BarrierClosedError",
    "HeartTransactionError",
    "IngressDuringTickError",
    "ValveDuringTickError",
    "CoreCommitError",
    "TickBindingError",
    "FinalCommitAlreadyMadeError",
    "LeaseDeniedError",
    "UnknownValveError",
    "ValveClosedError",
    "ValveBudgetExceededError",
    "ValveSourceMismatchError",
    "ValveAuthorityError",
    "ValveAdmissionError",
    "PoisonEventError",
    "ReplayEventError",
    "HealthCorruptionError",
    "HostStateError",
]
