# Re-export everything from the substrate module so `import substrate` works
# as a flat import (matching the archive convention).
from .substrate import *  # noqa: F403
from .substrate import (  # noqa: F401
    ALPHABET_SET,
    ASCENDERS,
    CLOSED_LOOPS,
    DESCENDERS,
    DOTS,
    EMPTY_SLOT,
    FEATURE_DIM,
    LETTER_FREQUENCY,
    LETTER_FREQUENCY_ORDER,
    MANNER_STOP,
    NASALITY,
    PLACE_H,
    PLACE_V,
    SLOT_DIM,
    SONORITY,
    VOICING,
    VOWELS_LOWER,
    WRITING_SET,
    LetterBank,
    assert_supported_text,
    build_basis_matrix,
    char_to_slot,
    default_alphabet,
    geometry_check,
    get_basis_matrix,
    get_letter_bank,
    roundtrip_check,
    structural_features,
    text_to_field,
    verify_substrate,
)
from .unicode_transport import (  # noqa: F401
    BYTE_TOKEN_COUNT,
    NATIVE_TOKEN_COUNT,
    TRANSPORT_VOCAB_SIZE,
    UNICODE_TRANSPORT_SCHEMA,
    EncodedUnicodeCharacter,
    InvalidUnicodeScalarError,
    MalformedUnicodeTransportError,
    NonCanonicalUnicodeTransportError,
    UnicodeTransportError,
    byte_token_id,
    byte_transport_bank,
    decode_unicode_tokens,
    encode_unicode_character,
    encode_unicode_text,
    native_token_id,
    transport_token_cell16,
    transport_token_kind,
    transport_token_value,
    unicode_transport_bank,
    unicode_transport_bank_sha256,
    unicode_transport_geometry,
)
