# Re-export everything from the substrate module so `import substrate` works
# as a flat import (matching the archive convention).
from .substrate import *  # noqa: F401,F403
from .substrate import (  # noqa: F401
    SLOT_DIM,
    FEATURE_DIM,
    VOWELS_LOWER,
    ASCENDERS,
    DESCENDERS,
    DOTS,
    CLOSED_LOOPS,
    LETTER_FREQUENCY_ORDER,
    LETTER_FREQUENCY,
    PLACE_H,
    PLACE_V,
    VOICING,
    NASALITY,
    SONORITY,
    MANNER_STOP,
    EMPTY_SLOT,
    ALPHABET_SET,
    WRITING_SET,
    assert_supported_text,
    structural_features,
    build_basis_matrix,
    get_basis_matrix,
    char_to_slot,
    text_to_field,
    default_alphabet,
    LetterBank,
    get_letter_bank,
    geometry_check,
    roundtrip_check,
    verify_substrate,
)
